export const HttpResponse = {
    SERVER_ERROR: "Internel server error",
    USER_EXIST: "User already exist",
    PAGE_NOT_FOUND: "Route not found",
    USER_NOT_FOUND: "User not found",
    NO_ACCESS_TOKEN: "Token not provided",
    NO_REFRESH_TOKEN: "Refresh token not provided",
    NO_TOKEN: "Token not provided",
    NO_DECODED_TOKEN: "Couldn't decode token",
    USER_ID_REQUIRED: "User ID is required",
    PUBLIC_ID_NOT_FOUND: "Cloudinary publicId not found",
    UNEXPECTED_KEY_FOUND: "Unexpected key found",
    INVALID_CREDENTIALS: "Invalid credentials",
    MISSING_OR_INVALID_FIELDS: "Missing or invalid required fields",
    POST_ADDED: "Post added successfully",
    POST_UPDATED: "Post updated successfully",
    POST_DELETED: "Post deleted successfully",
    BLOG_ID_REQUIRED: "Blog Id is required",
    COMMENT_ID_REQUIRED: "Comment Id is required",
    BLOG_NOT_FOUND: "Blog not found",
    LIKE_UPDATED: "Like status updated",
    COMMENT_ADDED: "Comment created successfully",
    COMMEND_UPDATED: "Comment updated successfully",
    COMMENT_REMOVED: "Comment removed successfully",
    COMMENTS_NOT_FOUND: "Comments not found",
    COMMENT_NOT_FOUND: "Comment not found",
    SUB_COMMENT_ADDED: "Sub comment added",
    SUB_COMMENT_NOT_FOUND: "Sub comment not found",
    SUB_COMMENT_REMOVED: "Sub comment removed successfully",
    SELF_FOLLOW_ERROR: "User can't follow himself",
    SELF_UNFOLLOW_ERROR: "User can't unfollow himself",
    USER_FOLLOWED: "Followed user successfully",
    USER_UNFOLLOWED: "Unfollowed user successfully",
    FOLLOWER_EXIST: "User already following",
    BOTH_USER_IDS_REQUIRED: "Both user IDs are required",
    
}